[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hqb3454", email = "3454565601@qq.com" }
]
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.9",
    "google-genai>=2.28.0",
    "python-dotenv>=1.2.4",
    "sentence-transformers>=6.1.0",
]

[project.scripts]
rag = "rag:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
